baseURL = 'https://hacobbe-cpu.github.io/qubee-site/'
languageCode = 'pl-pl'
title = '@kjaszczuk:~$'
theme = "shibui"

[params]
  author = "Your Name"
  email = "hacobbe@gmail.com"

[menu]
  [[menu.main]]
    name = "Posty"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "O mnie"
    url = "/about/"
    weight = 2