baseURL = 'https://hacobbe-cpu.github.io/qubee-site/'
languageCode = 'pl-pl'
title = 'Moja Minimalistyczna Strona'
theme = 'hugo-xmin'

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "O mnie"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posty"
    url = "/posts/"
    weight = 3