baseURL = 'https://kubajaszczuk.com/'
languageCode = 'pl-pl'
title = '@kjaszczuk:~$'
theme = "shibui-master"

[params]
  [params.author]
    name = "@kjaszczuk:~$"
  email = "hacobbe@gmail.com"

[[menu.main]]
    name = "O mnie"
    url = "/about/"
    weight = 1
[menu]
  [[menu.main]]
    name = "Posty"
    url = "/posts/"
    weight = 2
